### ISSUE TITLE
Guidelines on upgrading the Postgres version

### ISSUE THREAD

**Issue by s4ke** [citusdata/pg_auto_failover#506] opened 2020-11-12 19:00 UTC
Hey,

Since Postgres 13 has been out for a while now we are looking into upgrading because of some performance improvements and index size improvements it brings. Now I am wondering what the standard upgrade procedure for a pg_auto_failover cluster is.

I would guess:

1. Upgrade to the latest minor version via standard procedures (enable maintenance mode, upgrade one by one, restart, etc.)

I think it will be mostly similar to the standard procedure outlined in the docs at https://www.postgresql.org, but what should we be doing additionally?

**Comment by kevinelliott** [comment] 2020-12-05 22:22
I am also curious about this.

**Comment by DimCitus** [comment] 2020-12-07 11:13
Hi @s4ke and @kevinelliott ; thanks for opening this issue. At the moment pg_auto_failover does not include smart orchestration of Postgres restarts (for minor upgrades) or major upgrades. Sometimes I try to sketch how that would work, and it's not simple to integrate that into our machinery in a way that just works for the users.

When applying a manual procedure for major Postgres upgrades I believe the same steps as documented in Postgres itself should work with pg_auto_failover. What needs to be checked is if the `system_identifier` is impacted (I believe it is not), as this piece of information is maintained in the monitor and we don't have a API to update it to a new value. 

There is an extra step to implement with `pg_autoctl` when doing a major Postgres update though:

```
$ pg_autoctl config get postgresql.pg_ctl
$ pg_autoctl config get postgresql.pg_ctl /usr/lib/postgresql/13/bin/pg_ctl
```

When trying on a staging environment, please share here other steps you find that are needed on top of that. I am closing this issue for triaging purposes, feel free to re-open with more information / questions of course.

**Closed by DimCitus** 2020-12-07 11:13 UTC
Labels: docs, question

**Comment by s4ke** [comment] 2020-12-07 14:07
Okay, Thanks for the answer! I feel like this is probably not a task that pg_auto_failover itself should try to handle. I will let you know my findings once I play around with a playbook in our ansible repo.

**Comment by s4ke** [comment] 2020-12-11 20:57
@DimCitus When upgrading a cluster, should the monitor be upgraded first or last?

**Comment by kevinelliott** [comment] 2022-05-12 19:53
@s4ke Did you ever document the steps to upgrade Postgres major versions? I would like to upgrade from 13 to 14 and am curious to know what you may have done.

**Comment by s4ke** [comment] 2022-05-12 22:10
@kevinelliott I haven't had to run an in place upgrade yet, but what I guess will always work is to do the following:

1. Create a new node as secondary in existing cluster as secondary without quorum
2. Let the new node synchronize fully
3. remove the new node from existing cluster
4. upgrade the new node to new version
5. create new monitor node
6. join the existing cluster with the new node as its primary
7. add a new secondary to the new cluster

But that is just one way to achieve this. Essentially there is always the brute-force method of removing pg_autofailover from the picture and then building it ontop again. The same goes for backups

**Comment by woutsanders** [comment] 2023-02-14 17:28
Small update: I looked at the source code that writes the state file. Based on that I opened the file in my hex editor and changed it to the new system identifier manually. After starting pg_autoctl notified about a new catalog version, but that was it. Running without complaints now and shows up as a single node (as intended as I explicitly removed the secondary, which can be rebuilt later).
