### ISSUE TITLE
Monitor listener process tries to reconnect to monitor database without backoff

### ISSUE THREAD

**Issue by JelteF** [citusdata/pg_auto_failover#708] opened 2021-05-19 15:43 UTC
When postgres crashes for some reason logs are flooded with output like this:
![image](https://user-images.githubusercontent.com/1162278/118842724-bd5f2a80-b8c9-11eb-8f48-f89274496e64.png)

We should have a retry mechanism with a backoff here.

**Comment by DimCitus** [comment] 2021-10-05 12:02
Trying to reproduce with `kill -9` on the monitor's Postgres pid, but I get the expected retry mechanism. Closing this issue as a can't reproduce then. If you can think of another way to hit the bug you had at the time, please re-open with details!

```
14:00:45 60638 WARN  FATAL:  terminating connection due to unexpected postmaster exit
14:00:45 60638 ERROR Failed to LISTEN "state": server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.

14:00:45 60638 WARN  Re-establishing connection. We might miss notifications.
14:00:45 60638 WARN  Failed to connect to "postgres://autoctl_node@/tmp:5500/pg_auto_failover?", retrying until the server is ready
14:00:45 61690 INFO   /Applications/Postgres.app/Contents/Versions/12/bin/postgres -D /Users/dim/dev/MS/pg_auto_failover/tmux/monitor -p 5500 -h *
14:00:45 60638 WARN  The server at "postgres://autoctl_node@/tmp:5500/pg_auto_failover?" is running but is in a state that disallows connections (startup, shutdown, or crash recovery).
14:00:45 60637 WARN  PostgreSQL was not running, restarted with pid 61690
14:00:45 60638 INFO  Successfully connected to "postgres://autoctl_node@/tmp:5500/pg_auto_failover?" after 3 attempts in 597 ms.
```

**Closed by DimCitus** 2021-10-05 12:02 UTC
Labels: bug, Size: S
