### ISSUE TITLE
Expected a non-negative integer value on number of sync standbys

### ISSUE THREAD

**Issue by dudewithaface** [citusdata/pg_auto_failover#929] opened 2022-08-31 17:12 UTC
Hello,
I have been testing a setup with this tool. I have a monitor with 3 nodes connected and have tried to change the number of sync standbys. I run and get
```BASH
$ pg_autoctl set formation number-sync-standbys 0
ERROR number-sync-standbys value 0 is not valid. Expected a non-negative integer value.
```

I also tried setting it to 1 but I get the same error. 

Thanks in advance,
Tobias

**Comment by zlianzhuang** [comment] 2022-09-10 09:33
what is your version?  i am right on v1.6.4

**Comment by dudewithaface** [comment] 2022-09-12 15:10
```BASH
$ pg_autoctl --version
pg_autoctl version 1.6.3
pg_autoctl extension version 1.6
compiled with PostgreSQL 14.1 (Ubuntu 14.1-1ubuntu1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.2.0-12ubuntu1) 11.2.0, 64-bit
compatible with Postgres 10, 11, 12, 13, and 14
```
I installed through apt and I don't have any updates. I guess v1.6.4 isn't up yet.

**Comment by DimCitus** [comment] 2022-10-06 12:31
Closing the issue because I can't reproduce here. Consider using the latest release of pg_auto_failover as listed on this page: https://github.com/citusdata/pg_auto_failover/releases. For that you might want to use [apt.postgresql.org](https://apt.postgresql.org).

**Closed by DimCitus** 2022-10-06 12:31 UTC
