### ISSUE TITLE
BUG: Failed to parse pg_controldata output

### ISSUE THREAD

**Issue by meiyifei** [citusdata/pg_auto_failover#26] opened 2019-06-18 03:15 UTC
```
[postgres@test1 ~]$ pg_autoctl create monitor --pgdata ./pgdata
10:59:54 INFO  Initialising a PostgreSQL cluster at "./pgdata"
10:59:54 INFO  Now using absolute pgdata value "/home/postgres/pgdata" in the configuration
10:59:54 INFO   /usr/pgsql-11/bin/pg_ctl --pgdata ./pgdata --options "-p 5432" --options "-h *" --wait start
10:59:54 ERROR Failed to parse pg_controldata output
10:59:54 FATAL Failed to discover PostgreSQL setup, please fix previous errors.
10:59:54 FATAL Failed to initialise a monitor node, see above for details
```

**Comment by meiyifei** [comment] 2019-06-18 03:42
[resolve]:
$sudo localectl set-locale LANG=en_US.utf8
reboot
[postgres@test1 ~]$ echo $LANG
en_US.utf8
[postgres@test1 ~]$ pg_autoctl create monitor --pgdata ./pgdata
11:40:37 INFO  Initialising a PostgreSQL cluster at "./pgdata"
11:40:37 INFO  Now using absolute pgdata value "/home/postgres/pgdata" in the configuration
11:40:37 INFO   /usr/pgsql-11/bin/pg_ctl --pgdata ./pgdata --options "-p 5432" --options "-h *" --wait start
11:40:38 INFO  Granting connection privileges on 192.168.0.0/22
11:40:38 INFO  Your pg_auto_failover monitor instance is now ready on port 5432.
11:40:38 INFO  pg_auto_failover monitor is ready at postgres://autoctl_node@test1:5432/pg_auto_failover
11:40:38 INFO  Monitor has been succesfully initialized.

**Comment by DimCitus** [comment] 2019-06-18 08:20
Hi @meiyifei !

So it seems that the problem is with `ERROR Failed to parse pg_controldata output` then. We should probably force the LANG environment to be set to C when we parse the output of the PostgreSQL commands run internally in `pg_autoctl`. 

Thanks for your feedback. Marking this issue as a bug and assigning it to the next release, I think we should be able to have a fix that soon!

**Closed** 2019-06-20 13:05 UTC
Labels: bug
